services:
  fastexpress:
    image: fastexpress:1.0
    ports: 
      - 3000:3000
    environment:
    - MONGODB_USER=admin
    - MONGODB_PASSWORD=password
    - MONGODB_HOST=mongodb
    - MONGODB_PORT=27017
    - MONGODB_DATABASE=tower7
    depends_on:
      - mongodb
    volumes:
      - uploads_data:/home/app/uploads # El volumen se monta sobre la carpeta que ya tiene permisos de 'node'
  mongodb:
    image: mongo:noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db_data:/data/db
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

# Aquí se declaran los volúmenes globales
volumes:
  db_data: # Para MongoDB
  uploads_data: # Para tus archivos